/**
 * Copyright (c) TIBCO Software Inc 2004-2009. All rights reserved.
 */
package com.tibco.xpd.sce.tests.validation;

import com.tibco.xpd.core.test.util.TestResourceInfo;
import com.tibco.xpd.core.test.validations.ValidationsTestProblemMarkerInfo;
import com.tibco.xpd.n2.test.core.validation.AbstractN2BaseValidationTest;

/**
 * Ace5132DuplicateCatchSignalValidationTest
 * <p>
 * Ace5132DuplicateCatchSignalValidationTest - Test selected validations are correctly raised.
 * </p>
 * <p>
 * Generated by: createBaseTest.javajet
 * </p>
 *
 * Tests for duplicate catch same local signal on same task validation rule introduced by ACE-5132
 *
 * @author
 * @since
 */
public class Ace5132DuplicateCatchSignalValidationTest extends AbstractN2BaseValidationTest {

	public Ace5132DuplicateCatchSignalValidationTest() {
		super(true);
	}

	/**
     * Ace5132DuplicateCatchSignalValidationTest
     * 
     * @throws Exception
     */
    public void testAce5132DuplicateCatchSignalValidationTest() throws Exception {
		doTestValidations();        
        return;
	}

	@Override
    protected ValidationsTestProblemMarkerInfo[] getValidationProblemMarkerInfos() {
        ValidationsTestProblemMarkerInfo[] markerInfos = new ValidationsTestProblemMarkerInfo[] { 
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/CatchGLobalSIgnal/Process Packages/CatchGLobalSIgnal.xpdl", //$NON-NLS-1$ 
			    		"bpmn.dev.errorDuplicateCatchLocal", //$NON-NLS-1$ 
			    		"_orYHoMkqEeuaY_8KgDq4hg", //$NON-NLS-1$ 
			    		"BPM  : The signal 'Signal1' is already caught by event 'Catch: Signal1 (2)' on this task's boundary.  (CatchGLobalSIgnalProcess:CatchSignal14)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/CatchGLobalSIgnal/Process Packages/CatchGLobalSIgnal.xpdl", //$NON-NLS-1$ 
			    		"bpmn.dev.errorDuplicateCatchLocal", //$NON-NLS-1$ 
			    		"_OVoi8MkqEeuaY_8KgDq4hg", //$NON-NLS-1$ 
			    		"BPM  : The signal 'Signal1' is already caught by event 'Catch: Signal1 (2)' on this task's boundary.  (CatchGLobalSIgnalProcess:CatchSignal13)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			
			    new ValidationsTestProblemMarkerInfo(
			    		"/CatchGLobalSIgnal/Process Packages/CatchGLobalSIgnal.xpdl", //$NON-NLS-1$ 
			    		"bx.processHasNoMigrationPoints", //$NON-NLS-1$ 
			    		"_SlwjEMkkEeuOWu44Zd8nmg", //$NON-NLS-1$ 
			    		"BPM  : There are no migration point activities in the process. No migration of any existing run-time process instances to new process version will be possible. (CatchGLobalSIgnalProcess)", //$NON-NLS-1$ 
			    		""), //$NON-NLS-1$ 
			    		
			                
        };
        return markerInfos;
    }

    @Override
    protected String getTestName() {
        return "Ace5132DuplicateCatchSignalValidationTest"; //$NON-NLS-1$
    }

    @Override
    protected String getTestPlugInId() {
        return "com.tibco.xpd.sce.test"; //$NON-NLS-1$
    }

    @Override
    protected TestResourceInfo[] getTestResources() {
        TestResourceInfo[] testResources = new TestResourceInfo[] {
            new TestResourceInfo("resources/Ace5132DuplicateCatchSignalValidationTest", "CatchGLobalSIgnal/Process Packages{processes}/CatchGLobalSIgnal.xpdl"), //$NON-NLS-1$ //$NON-NLS-2$
        };
    
        return testResources;
    }

}
